packages:
  - '.'
  - 'packages/*'
  - 'lightgallery-react'
  - 'lightgallery-vue'
  - 'lightgallery-lit'
  - 'lightgallery-angular/*'

overrides:
  '@types/babel__traverse': 7.11.1
  '@types/express': 4.17.11
  '@types/express-serve-static-core': 4.17.19
  '@types/react': 18.0.15
  '@types/serve-static': 1.13.10
